# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus-connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_role', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Event',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default=b'', max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.AddField(
            model_name='student',
            name='member_of_clubs',
            field=models.ManyToManyField(blank=True, default=None, related_name='members', to='campus-connect.Club'),
        ),
        migrations.AddField(
            model_name='student',
            name='officer_of_club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='campus-connect.Club'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
