# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus-connect', '0003_auto_20170327_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='officer_of_club',
        ),
    ]
