# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus-connect', '0005_studentuser_officer_of_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='member_of_clubs',
            field=models.ManyToManyField(to='campus-connect.Club'),
        ),
    ]
