# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus-connect', '0007_auto_20170327_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='member_of_clubs',
            field=models.ManyToManyField(blank=True, default=None, to='campus-connect.Club'),
        ),
    ]
