# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus-connect', '0008_auto_20170327_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentUser',
            new_name='Student',
        ),
    ]
