# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus-connect', '0009_auto_20170327_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='member_of_clubs',
            field=models.ManyToManyField(blank=True, default=None, related_name='members', to='campus-connect.Club'),
        ),
        migrations.AlterField(
            model_name='student',
            name='officer_of_club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='campus-connect.Club'),
        ),
    ]
