# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus-connect', '0010_auto_20170327_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Event',
        ),
    ]
