# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus-connect', '0011_auto_20170327_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
